import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Libs {
    const val klaxon: String = "com.beust:klaxon:" + Versions.klaxon

    /**
     * [converter-scalars website](https://github.com/square/retrofit/) */
    const val converter_scalars: String =
            "com.squareup.retrofit2:converter-scalars:" + Versions.com_squareup_retrofit2

    /**
     * [retrofit website](https://github.com/square/retrofit/) */
    const val retrofit: String =
            "com.squareup.retrofit2:retrofit:" + Versions.com_squareup_retrofit2

    const val de_fuerstenau_buildconfig_gradle_plugin: String =
            "de.fuerstenau.buildconfig:de.fuerstenau.buildconfig.gradle.plugin:" + Versions.de_fuerstenau_buildconfig_gradle_plugin

    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "jmfayard.github.io.gradle-kotlin-dsl-libs:jmfayard.github.io.gradle-kotlin-dsl-libs.gradle.plugin:" + Versions.jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin

    /**
     * [funktionale-memoization website](https://github.com/MarioAriasC/funKTionale) */
    const val funktionale_memoization: String =
            "org.funktionale:funktionale-memoization:" + Versions.funktionale_memoization

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:" + Versions.org_jetbrains_kotlin_jvm_gradle_plugin

    /**
     * [kotlin-reflect website](https://kotlinlang.org/) */
    const val kotlin_reflect: String =
            "org.jetbrains.kotlin:kotlin-reflect:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-scripting-compiler-embeddable website](https://kotlinlang.org/) */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-stdlib-jdk8 website](https://kotlinlang.org/) */
    const val kotlin_stdlib_jdk8: String =
            "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-test website](https://kotlinlang.org/) */
    const val kotlin_test: String =
            "org.jetbrains.kotlin:kotlin-test:" + Versions.org_jetbrains_kotlin

    /**
     * [spek-api website](https://jetbrains.github.io/spek) */
    const val spek_api: String = "org.jetbrains.spek:spek-api:" + Versions.org_jetbrains_spek

    /**
     * [spek-junit-platform-engine website](https://jetbrains.github.io/spek) */
    const val spek_junit_platform_engine: String =
            "org.jetbrains.spek:spek-junit-platform-engine:" + Versions.org_jetbrains_spek

    const val org_jmailen_kotlinter_gradle_plugin: String =
            "org.jmailen.kotlinter:org.jmailen.kotlinter.gradle.plugin:" + Versions.org_jmailen_kotlinter_gradle_plugin

    /**
     * [junit-platform-gradle-plugin website](http://junit.org/junit5/) */
    const val junit_platform_gradle_plugin: String =
            "org.junit.platform:junit-platform-gradle-plugin:" + Versions.junit_platform_gradle_plugin
}
