import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val io_gitlab_arturbosch_detekt: String = "1.2.0"

    const val org_spekframework_spek2: String = "2.0.8"

    const val com_squareup_retrofit2: String = "2.6.2"

    const val org_jetbrains_kotlin: String = "1.3.61"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val de_fuerstenau_buildconfig_gradle_plugin: String = "1.1.8"

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String = "1.3.61"

    const val funktionale_memoization: String = "1.2"

    const val klaxon: String = "5.2"

    /**
     * Current version: "6.0.1"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.0.1"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
